# Damn Vulnerable NodeJS Application

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
#    volumes:
#      - .:/app
#      - /app/node_modules
    depends_on:
      - db
    env_file:
      - ./vars.env

  db:
    image: postgres:13
#    expose:
#      - "3306"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./vars.env

volumes:
  pgdata: