name: "ZAP Baseline Scan"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    permissions:
      issues: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run ZAP Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://dvna.blueisland-aa8261f7.canadaeast.azurecontainerapps.io'
          cmd_options: '-a'